import Head from 'next/head'

import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Feel your body</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        edededededddd
        
      </main>

      <footer className={styles.footer}>
        wdwdwdwd
      </footer>
    </div>
  )
}
