import Head from 'next/head'
//import HeaderBlock from '../components/header-block/header-block'
import styles from '../styles/Home.module.scss'
import header from '../components/header-block/header-block.module.scss'
//import HeaderBlock from '../components/header-block'
import BodyBlock from '../components/body-block/body-block'
import React, { PureComponent } from 'react'


class Home extends PureComponent {
    render() {
        return (
            <div className={styles.wrapper}>
                <Head>
                    <title>Feel your body</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <div className={header.wrapper}>
                    <div className={header.header}>

                    </div>
                    <div className='body'>

                    </div>
                    Відчуй своє тіло
                </div>
                <BodyBlock />
                <div className='body-block'>
                    Від масажу більше користі, ніж Ви уявляєте
                </div>
                <div className='about-me'>
                    Давайте знайомитись
                </div>
                <div className='my-philosophy'>

                </div>
                <div className='my-services'>
                    Послуги
                </div>
                <div className='customer-reviews'>
                    Відгуки моїх клієнтів
                </div>
            </div>
        )
    }
}

export default Home